### ISSUE TITLE
multipleResolves is deprecated.

### ISSUE THREAD

**Issue by ghost** [KauaAmaroPires/Download_Youtube#2]
This issue is not system breaking of any form, but it is a simple thing that I hoped can be fixed.

```
(node:9070) [DEP0160] DeprecationWarning: The multipleResolves event has been deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

I like this project a lot and I enjoy just installing it on many device without much overhead. I look forward to the future changes!

**Comment by KauaAmaroPires** [comment]
hello friend, i am happy that you are enjoying the project, i did the updates of the library versions and now everything is up to date, i also saw about this message, it can be shown depending on your version of node.js, because of it is higher than recommended by the library and etc..., I am using version 16.17.0, try using this one to resolve this message.

**Comment by ghost** [comment]
I understand that, but I personally need the latest lts for many projects. Lucky I have NVM (node version manager).

**Comment by KauaAmaroPires** [comment]
@pendragons-code, hello friend, sorry again for the delay, I solved the `multipleResolves deprecated` problem, thanks for reporting

**Comment by ghost** [comment]
Thank you very much!
